/**
 * Focus Mode — structured concept maps generated by the offline model and
 * rendered as a zoomable node workspace.
 *
 * The 0.5B-class local model can't be trusted to emit pixel-perfect UI
 * instructions, so it's asked for *data* (a strict JSON concept map) and the
 * app renders it deterministically. If the JSON comes back malformed, a
 * tolerant parser rescues whatever it can; if even that fails, the raw text
 * is split into sections and laid out as a linear chain — the workspace is
 * never empty.
 */

export type FocusNodeKind =
  | "topic"
  | "definition"
  | "type"
  | "component"
  | "process"
  | "example"
  | "application"
  | "importance"
  | "note";

export interface FocusNode {
  id: string;
  label: string;
  kind: FocusNodeKind;
  /** Short caption — the only text shown on the node card itself. */
  summary: string;
  /** Full explanation — shown when the node is opened. */
  detail: string;
}

export interface FocusLink {
  from: string;
  to: string;
  label?: string;
}

export interface FocusMap {
  id: string;
  topic: string;
  createdAt: number;
  nodes: FocusNode[];
  links: FocusLink[];
  /**
   * Learning journey (cloud maps): an ordered partition of the nodes into
   * stages. Offline maps have none — the journey view falls back to one
   * linear stage.
   */
  stages?: JourneyStage[];
}

export interface JourneyStage {
  id: string;
  title: string;
  objective: string;
  /** Ordered node ids shown in this stage. */
  conceptIds: string[];
}

export const FOCUS_KINDS: FocusNodeKind[] = [
  "topic",
  "definition",
  "type",
  "component",
  "process",
  "example",
  "application",
  "importance",
  "note",
];

/** Palette used by the workspace — readable on both the glass and pop themes. */
export const KIND_META: Record<FocusNodeKind, { color: string; label: string }> = {
  topic: { color: "#C6FF3D", label: "Topic" },
  definition: { color: "#6FD9E8", label: "Definition" },
  type: { color: "#4FC3DC", label: "Types" },
  component: { color: "#60A5FA", label: "Components" },
  process: { color: "#34D399", label: "Process" },
  example: { color: "#F472B6", label: "Example" },
  application: { color: "#22D3EE", label: "Applications" },
  importance: { color: "#FBBF24", label: "Why it matters" },
  note: { color: "#94A3B8", label: "Note" },
};

const MAX_NODES = 14;

function isKind(v: unknown): v is FocusNodeKind {
  return typeof v === "string" && (FOCUS_KINDS as string[]).includes(v);
}

function clean(text: string): string {
  return (text ?? "").replace(/\s+/g, " ").trim();
}

/**
 * Try to read a FocusMap out of the model's raw output. Returns null when
 * the text contains no recoverable JSON structure with at least 2 nodes —
 * callers then fall back to the linear builder.
 */
export function parseFocusMap(raw: string, topic: string): FocusMap | null {
  if (!raw) return null;

  // Strip markdown fences — models love to wrap JSON in ```json blocks.
  let text = raw.replace(/```(?:json)?/gi, "").trim();
  const start = text.indexOf("{");
  const end = text.lastIndexOf("}");
  if (start === -1 || end === -1 || end <= start) return null;
  text = text.slice(start, end + 1);

  let parsed: unknown;
  try {
    parsed = JSON.parse(text);
  } catch {
    return null;
  }
  if (!parsed || typeof parsed !== "object") return null;
  const obj = parsed as Record<string, unknown>;

  const nodesRaw = Array.isArray(obj.nodes) ? obj.nodes : [];
  const nodes: FocusNode[] = [];
  for (const n of nodesRaw.slice(0, MAX_NODES)) {
    if (!n || typeof n !== "object") continue;
    const node = n as Record<string, unknown>;
    const label = clean(typeof node.label === "string" ? node.label : "");
    if (!label) continue;
    nodes.push({
      id:
        typeof node.id === "string" && node.id
          ? node.id.replace(/[^a-zA-Z0-9_-]/g, "")
          : `n${nodes.length + 1}`,
      label,
      kind: isKind(node.kind) ? node.kind : "note",
      summary: clean(typeof node.summary === "string" ? node.summary : ""),
      detail: clean(typeof node.detail === "string" ? node.detail : ""),
    });
  }
  if (nodes.length < 2) return null;

  const ids = new Set(nodes.map((n) => n.id));
  const links: FocusLink[] = [];
  const linksRaw = Array.isArray(obj.links) ? obj.links : [];
  for (const l of linksRaw) {
    if (!l || typeof l !== "object") continue;
    const link = l as Record<string, unknown>;
    const from = typeof link.from === "string" ? link.from : "";
    const to = typeof link.to === "string" ? link.to : "";
    if (!from || !to || from === to) continue;
    if (!ids.has(from) || !ids.has(to)) continue;
    links.push({
      from,
      to,
      label: clean(typeof link.label === "string" ? link.label : "") || undefined,
    });
  }

  return {
    id: `focus-${Date.now()}`,
    topic: clean(topic) || (typeof obj.topic === "string" ? clean(obj.topic) : "Concept map"),
    createdAt: Date.now(),
    nodes,
    links,
  };
}

function summarize(text: string, max = 120): string {
  const t = clean(text);
  if (t.length <= max) return t;
  const cut = t.slice(0, max);
  return cut.slice(0, cut.lastIndexOf(" ")) + "…";
}

/**
 * Last-resort builder: when the model's JSON is unusable, turn its raw
 * explanation into a linear chain of cards so the workspace still works.
 */
export function fallbackFocusMap(raw: string, topic: string): FocusMap {
  const nodes: FocusNode[] = [];
  const links: FocusLink[] = [];

  const rootId = "root";
  nodes.push({
    id: rootId,
    label: clean(topic) || "Concept",
    kind: "topic",
    summary: summarize(raw || "A breakdown of this topic.", 110),
    detail: clean(raw || "The model couldn't structure this topic, so here's its explanation."),
  });

  // Split into sections by markdown headings or numbered points.
  const sections = (raw || "")
    .split(/\n(?=#{1,3}\s|\d+[.)]\s|[-*]\s)/)
    .map((s) => s.trim())
    .filter((s) => s.length > 12)
    .slice(0, 8);

  let prev = rootId;
  sections.forEach((section, i) => {
    const headingMatch = section.match(/^#{1,3}\s+(.+)$/m);
    const numberedMatch = section.match(/^\d+[.)]\s+(.+)$/m);
    const rawLabel =
      headingMatch?.[1]?.trim() ??
      numberedMatch?.[1]?.trim() ??
      clean(section.split("\n")[0] ?? "").slice(0, 60);
    const body = section
      .replace(/^#{1,3}\s+.+$/m, "")
      .replace(/^\d+[.)]\s+/, "")
      .trim();
    const id = `s${i + 1}`;
    nodes.push({
      id,
      label: rawLabel || `Point ${i + 1}`,
      kind: i === 0 ? "definition" : "note",
      summary: summarize(body || rawLabel, 110),
      detail: clean(body || section),
    });
    links.push({ from: prev, to: id });
    prev = id;
  });

  return {
    id: `focus-${Date.now()}`,
    topic: clean(topic) || "Concept map",
    createdAt: Date.now(),
    nodes,
    links,
  };
}

// ── Cloud backend types + adapter ──────────────────────────────
// Focus Mode is now a cloud-powered Magic Plus feature: the mobile app asks
// the Matriq backend (which securely calls DeepSeek) for a structured JSON
// concept map, then renders it deterministically here. These types mirror the
// backend schema and are converted into the client FocusMap shape below so the
// existing layout/workspace logic is reused unchanged.

export interface BackendFocusConcept {
  id: string;
  label: string;
  kind:
    | "topic"
    | "definition"
    | "component"
    | "process"
    | "type"
    | "example"
    | "application"
    | "importance"
    | "prerequisite";
  summary: string;
  detail: string;
  importance?: string;
  examples?: string[];
  prerequisites?: string[];
  parents?: string[];
}

export interface BackendFocusStage {
  id: string;
  title: string;
  objective: string;
  conceptIds: string[];
}

export interface BackendFocusMap {
  version: "1.0" | "1.1";
  topic: string;
  overview: string;
  concepts: BackendFocusConcept[];
  stages?: BackendFocusStage[];
}

export interface BackendEntitlement {
  entitled: boolean;
  isPremium: boolean;
  plan: string | null;
  source: string | null;
  freeRemaining: number | null;
  freeUsed: number;
  freeLimit: number;
  expiresAt: string | null;
}

/** Convert the backend's structured map into the client render model. */
export function backendFocusMapToClient(b: BackendFocusMap): FocusMap {
  const concepts = b.concepts ?? [];
  const nodes: FocusNode[] = concepts.map((c) => ({
    id: c.id,
    label: c.label || c.id,
    kind: clientKind(c.kind),
    summary: c.summary || c.label || "",
    detail:
      c.kind === "topic"
        ? c.detail || b.overview || ""
        : c.detail || (c.importance ? `${c.importance}` : ""),
  }));

  // Build links from parent + prerequisite relationships (dedup, drop dangling).
  const links: FocusLink[] = [];
  const seen = new Set<string>();
  const ids = new Set(concepts.map((c) => c.id));
  for (const c of concepts) {
    const prereqs = c.prerequisites ?? [];
    const parents = c.parents ?? [];
    for (const p of [...parents, ...prereqs]) {
      if (!p || p === c.id || !ids.has(p)) continue;
      const key = `${p}->${c.id}`;
      if (seen.has(key)) continue;
      seen.add(key);
      links.push({
        from: p,
        to: c.id,
        label: prereqs.includes(p) ? "needs" : "part of",
      });
    }
  }

  return {
    id: `focus-${Date.now()}`,
    topic: b.topic || b.overview || "Concept map",
    createdAt: Date.now(),
    nodes,
    links,
    // Cloud maps carry the learning journey; offline maps leave it unset.
    ...(Array.isArray(b.stages) && b.stages.length > 0
      ? {
          stages: b.stages
            .map((s) => ({
              id: s.id || `stage-${s.title}`,
              title: s.title || "Next step",
              objective: s.objective || "Understand these ideas well.",
              conceptIds: (s.conceptIds ?? []).filter(
                (id) => !!id && ids.has(id),
              ),
            }))
            .filter((s) => s.conceptIds.length > 0),
        }
      : {}),
  };
}

function clientKind(
  k: BackendFocusConcept["kind"],
): FocusNodeKind {
  if ((FOCUS_KINDS as string[]).includes(k)) return k as FocusNodeKind;
  return "note";
}

// ── Deterministic layout ───────────────────────────────────────
// Levels come from a BFS from the root(s); each level becomes a column. This
// is stable across re-renders (positions depend only on the map), which is
// exactly what a node workspace needs.

export const NODE_W = 176;
export const NODE_H = 92;
const GAP_X = 56;
const GAP_Y = 30;
const MARGIN = 48;

export interface NodePosition {
  x: number;
  y: number;
}

export interface LayoutResult {
  positions: Record<string, NodePosition>;
  canvasWidth: number;
  canvasHeight: number;
}

export function layoutFocusMap(map: FocusMap): LayoutResult {
  const incoming = new Map<string, number>();
  for (const n of map.nodes) incoming.set(n.id, 0);
  for (const l of map.links) {
    incoming.set(l.to, (incoming.get(l.to) ?? 0) + 1);
  }

  // BFS from every root (nodes with no incoming link), ordered by appearance.
  const levelOf = new Map<string, number>();
  let frontier = map.nodes.filter((n) => (incoming.get(n.id) ?? 0) === 0);
  if (frontier.length === 0 && map.nodes.length > 0) {
    frontier = [map.nodes[0]];
  }
  let level = 0;
  while (frontier.length > 0) {
    const next: FocusNode[] = [];
    for (const n of frontier) {
      if (levelOf.has(n.id)) continue;
      levelOf.set(n.id, level);
      for (const l of map.links) {
        if (l.from === n.id) {
          const child = map.nodes.find((c) => c.id === l.to);
          if (child) next.push(child);
        }
      }
    }
    frontier = next;
    level += 1;
    if (level > 40) break; // safety
  }

  // Anything unreachable lands in the last column, in node order.
  let orphanLevel = level;
  for (const n of map.nodes) {
    if (!levelOf.has(n.id)) {
      levelOf.set(n.id, orphanLevel);
    }
  }

  const byLevel = new Map<number, FocusNode[]>();
  for (const n of map.nodes) {
    const lv = levelOf.get(n.id) ?? 0;
    if (!byLevel.has(lv)) byLevel.set(lv, []);
    byLevel.get(lv)!.push(n);
  }

  const positions: Record<string, NodePosition> = {};
  let maxCols = 0;
  let maxRows = 0;
  for (const [lv, nodes] of byLevel) {
    maxCols = Math.max(maxCols, lv + 1);
    maxRows = Math.max(maxRows, nodes.length);
    const colX = MARGIN + lv * (NODE_W + GAP_X);
    nodes.forEach((n, i) => {
      const rowY =
        MARGIN +
        i * (NODE_H + GAP_Y) -
        ((nodes.length - 1) * (NODE_H + GAP_Y)) / 2;
      positions[n.id] = { x: colX, y: rowY };
    });
  }

  return {
    positions,
    canvasWidth: MARGIN * 2 + Math.max(1, maxCols) * NODE_W + (maxCols - 1) * GAP_X,
    canvasHeight: MARGIN * 2 + Math.max(1, maxRows) * NODE_H + (maxRows - 1) * GAP_Y,
  };
}
